"""Initial migration

Revision ID: 7d4329127879
Revises: 
Create Date: 2025-02-19 14:08:38.697387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d4329127879'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flat_additional_options')
    op.drop_index('ix_posts_id', table_name='posts')
    op.drop_index('ix_posts_title', table_name='posts')
    op.drop_table('posts')
    op.drop_index('ix_communication_type_id', table_name='communication_type')
    op.drop_table('communication_type')
    op.drop_index('ix_social_media_accounts_id', table_name='social_media_accounts')
    op.drop_table('social_media_accounts')
    op.drop_index('ix_additional_options_id', table_name='additional_options')
    op.drop_table('additional_options')
    op.drop_index('ix_works_id', table_name='works')
    op.drop_index('ix_works_title', table_name='works')
    op.drop_table('works')
    op.drop_index('ix_notifications_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_portfolio_posts_id', table_name='portfolio_posts')
    op.drop_table('portfolio_posts')
    op.drop_table('page_type')
    op.drop_index('ix_styles_id', table_name='styles')
    op.drop_table('styles')
    op.drop_index('ix_blog_blocks_id', table_name='blog_blocks')
    op.drop_table('blog_blocks')
    op.drop_index('ix_portfolio_post_texts_id', table_name='portfolio_post_texts')
    op.drop_table('portfolio_post_texts')
    op.drop_index('ix_flats_id', table_name='flats')
    op.drop_table('flats')
    op.drop_index('ix_intro_videos_id', table_name='intro_videos')
    op.drop_table('intro_videos')
    op.drop_index('ix_portfolio_post_videos_id', table_name='portfolio_post_videos')
    op.drop_table('portfolio_post_videos')
    op.drop_index('ix_user_comments_id', table_name='user_comments')
    op.drop_table('user_comments')
    op.drop_index('ix_paragraphs_id', table_name='paragraphs')
    op.drop_index('ix_paragraphs_title', table_name='paragraphs')
    op.drop_table('paragraphs')
    op.drop_index('ix_seo_texts_id', table_name='seo_texts')
    op.drop_table('seo_texts')
    op.drop_index('ix_blog_paragraphs_id', table_name='blog_paragraphs')
    op.drop_table('blog_paragraphs')
    op.drop_index('ix_consultation_list_id', table_name='consultation_list')
    op.drop_table('consultation_list')
    op.drop_table('notification_type')
    op.drop_index('ix_tariffs_id', table_name='tariffs')
    op.drop_table('tariffs')
    op.drop_index('ix_blog_videos_id', table_name='blog_videos')
    op.drop_table('blog_videos')
    op.drop_table('user_type')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.drop_table('project_type')
    op.drop_index('ix_work_status_id', table_name='work_status')
    op.drop_index('ix_work_status_title', table_name='work_status')
    op.drop_table('work_status')
    op.drop_index('ix_contracts_id', table_name='contracts')
    op.drop_table('contracts')
    op.drop_index('ix_faqs_heading', table_name='faqs')
    op.drop_index('ix_faqs_id', table_name='faqs')
    op.drop_table('faqs')
    op.drop_index('ix_blogs_id', table_name='blogs')
    op.drop_table('blogs')
    op.drop_index('ix_platform_news_id', table_name='platform_news')
    op.drop_index('ix_platform_news_title', table_name='platform_news')
    op.drop_table('platform_news')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_news',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='platform_news_pkey')
    )
    op.create_index('ix_platform_news_title', 'platform_news', ['title'], unique=False)
    op.create_index('ix_platform_news_id', 'platform_news', ['id'], unique=False)
    op.create_table('blogs',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('blogs_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('img_main', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('text_main', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='blogs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_blogs_id', 'blogs', ['id'], unique=False)
    op.create_table('faqs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('heading', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('key_word', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('page_tag_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['page_tag_id'], ['page_type.id'], name='faqs_page_tag_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='faqs_pkey')
    )
    op.create_index('ix_faqs_id', 'faqs', ['id'], unique=False)
    op.create_index('ix_faqs_heading', 'faqs', ['heading'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('contracts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('object', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('order_type', postgresql.ENUM('renovation', 'building', name='ordertype'), autoincrement=False, nullable=True),
    sa.Column('tariff_type', postgresql.ENUM('base', 'standard', 'comfort', 'business', name='tarifftype'), autoincrement=False, nullable=True),
    sa.Column('square', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_stage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total_cost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('materials_cost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('work_cost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('revenue', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('document', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name='contracts_client_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='contracts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_contracts_id', 'contracts', ['id'], unique=False)
    op.create_table('work_status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('document', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('contract_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name='work_status_contract_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='work_status_pkey')
    )
    op.create_index('ix_work_status_title', 'work_status', ['title'], unique=False)
    op.create_index('ix_work_status_id', 'work_status', ['id'], unique=False)
    op.create_table('project_type',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('project_type_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='project_type_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('surname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('patronymic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_referral_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('others_referral_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notification_status_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['notification_status_id'], ['notification_type.id'], name='users_notification_status_id_fkey'),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_type.id'], name='users_user_type_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('user_referral_code', name='users_user_referral_code_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('user_type',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_type_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_type_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('blog_videos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('video_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('video_duration', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('object', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='blog_videos_pkey')
    )
    op.create_index('ix_blog_videos_id', 'blog_videos', ['id'], unique=False)
    op.create_table('tariffs',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tariffs_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tariffs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_tariffs_id', 'tariffs', ['id'], unique=False)
    op.create_table('notification_type',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('notification_type_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='notification_type_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('consultation_list',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('answered', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('communication_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['communication_type_id'], ['communication_type.id'], name='consultation_list_communication_type_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='consultation_list_pkey')
    )
    op.create_index('ix_consultation_list_id', 'consultation_list', ['id'], unique=False)
    op.create_table('blog_paragraphs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('items', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('blog_block_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['blog_block_id'], ['blog_blocks.id'], name='blog_paragraphs_blog_block_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='blog_paragraphs_pkey')
    )
    op.create_index('ix_blog_paragraphs_id', 'blog_paragraphs', ['id'], unique=False)
    op.create_table('seo_texts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('page_tag_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['page_tag_id'], ['page_type.id'], name='seo_texts_page_tag_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='seo_texts_pkey')
    )
    op.create_index('ix_seo_texts_id', 'seo_texts', ['id'], unique=False)
    op.create_table('paragraphs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='paragraphs_post_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='paragraphs_pkey')
    )
    op.create_index('ix_paragraphs_title', 'paragraphs', ['title'], unique=False)
    op.create_index('ix_paragraphs_id', 'paragraphs', ['id'], unique=False)
    op.create_table('user_comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_comments_pkey')
    )
    op.create_index('ix_user_comments_id', 'user_comments', ['id'], unique=False)
    op.create_table('portfolio_post_videos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('duration', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('portfolio_post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='portfolio_post_videos_pkey')
    )
    op.create_index('ix_portfolio_post_videos_id', 'portfolio_post_videos', ['id'], unique=False)
    op.create_table('intro_videos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('video', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('video_duration', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('object', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='intro_videos_pkey')
    )
    op.create_index('ix_intro_videos_id', 'intro_videos', ['id'], unique=False)
    op.create_table('flats',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('flats_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('square', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('number_of_rooms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('number_of_doors', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('number_of_wc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('demolition', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('wall_build', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('liquid_floor', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ceiling_stretching', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('tariff_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('style_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], name='flats_style_id_fkey'),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], name='flats_tariff_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='flats_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_flats_id', 'flats', ['id'], unique=False)
    op.create_table('portfolio_post_texts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('steps_of_work', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('portfolio_post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['portfolio_post_id'], ['portfolio_posts.id'], name='portfolio_post_texts_portfolio_post_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='portfolio_post_texts_pkey')
    )
    op.create_index('ix_portfolio_post_texts_id', 'portfolio_post_texts', ['id'], unique=False)
    op.create_table('blog_blocks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('images', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('blog_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], name='blog_blocks_blog_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='blog_blocks_pkey')
    )
    op.create_index('ix_blog_blocks_id', 'blog_blocks', ['id'], unique=False)
    op.create_table('styles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('styles_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='styles_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_styles_id', 'styles', ['id'], unique=False)
    op.create_table('page_type',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='page_type_pkey')
    )
    op.create_table('portfolio_posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('img_main', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('img_result', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price_amount', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('object_area', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('work_completion_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('project_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('images', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_type_id'], ['project_type.id'], name='portfolio_posts_project_type_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='portfolio_posts_pkey')
    )
    op.create_index('ix_portfolio_posts_id', 'portfolio_posts', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('notification_status', postgresql.ENUM('sign_act', 'message', name='contractnotificationstatus'), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('attachment', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('contract_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name='notifications_contract_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifications_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    op.create_index('ix_notifications_id', 'notifications', ['id'], unique=False)
    op.create_table('works',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deadline', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('square', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('task', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('preview_image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('main_image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('result_image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('result_video', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('client_video', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='works_pkey')
    )
    op.create_index('ix_works_title', 'works', ['title'], unique=False)
    op.create_index('ix_works_id', 'works', ['id'], unique=False)
    op.create_table('additional_options',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('additional_options_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='additional_options_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_additional_options_id', 'additional_options', ['id'], unique=False)
    op.create_table('social_media_accounts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('logo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subscribers', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='social_media_accounts_pkey')
    )
    op.create_index('ix_social_media_accounts_id', 'social_media_accounts', ['id'], unique=False)
    op.create_table('communication_type',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='communication_type_pkey')
    )
    op.create_index('ix_communication_type_id', 'communication_type', ['id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('post_type', postgresql.ENUM('news', 'blog', name='posttype'), autoincrement=False, nullable=True),
    sa.Column('images', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='posts_pkey')
    )
    op.create_index('ix_posts_title', 'posts', ['title'], unique=False)
    op.create_index('ix_posts_id', 'posts', ['id'], unique=False)
    op.create_table('flat_additional_options',
    sa.Column('flat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('additional_option_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['additional_option_id'], ['additional_options.id'], name='flat_additional_options_additional_option_id_fkey'),
    sa.ForeignKeyConstraint(['flat_id'], ['flats.id'], name='flat_additional_options_flat_id_fkey'),
    sa.PrimaryKeyConstraint('flat_id', 'additional_option_id', name='flat_additional_options_pkey')
    )
    # ### end Alembic commands ###
