- name: Read .env file on localhost
  command: cat ../.env
  register: env_file_content
  changed_when: false

- name: Parse .env file into variables
  set_fact:
    env_vars: "{{ env_vars | combine({ item.split('=')[0]: item.split('=')[1] }) }}"
  loop: '{{ env_file_content.stdout_lines }}'
  changed_when: false

- name: Validate required variables
  ansible.builtin.fail:
    msg: '{{ item }} variable from .env file is not defined'
  when: env_vars[item] is not defined
  loop: '{{ required_vars_from_env }}'
