- name: set_environment
  hosts: '{{ hosts }}'
  # gather_facts: false
  become: true
  vars:
    - ansistrano_deploy_to: '{{remote_app_path}}/frontend/'
  tasks:
    - name: ansistrano deploy
      ansible.builtin.import_role:
        name: ansistrano.deploy
      vars:
        ansistrano_deploy_from: '{{ playbook_dir }}/../frontend'
        ansistrano_deploy_via: rsync
        ansistrano_rsync_extra_params: '--exclude=.vscode --exclude=.nuxt --exclude=.output --exclude=node_modules  --exclude=.build'

    - name: install pnpm dependencies
      ansible.builtin.command:
        cmd: pnpm install
        chdir: '{{ ansistrano_deploy_to }}/current/frontend'

    - name: make build
      ansible.builtin.command:
        cmd: pnpm build
        chdir: '{{ ansistrano_deploy_to }}/current/frontend'

    - name: start/restart pm2 frontend process
      ansible.builtin.command:
        cmd: pm2 start ecosystem.config.js
        chdir: '{{ remote_app_path }}'
