############### повторяющаяся шапка
- name: Read .env file and create user
  hosts: localhost
  gather_facts: false
  tasks:
    - name: set variables from .env to facts
      ansible.builtin.include_tasks: tasks/set__env_vars__from_.env.yml

- name: Use parsed .env variables on remote host
  hosts: remote-staging-user
  # gather_facts: false
  become: true
  tasks:
    - name: Pass variables to remote host
      set_fact:
        remote_env_vars: "{{ hostvars['localhost']['env_vars'] }}"
    ###################################

    - name: install nodejs
      include_role: name=geerlingguy.nodejs
      vars:
        nodejs_version: '20.x'

    - name: Install pnpm globally using npm
      ansible.builtin.npm:
        name: pnpm
        global: yes
        state: present

    - name: Install pm2 globally using npm
      ansible.builtin.npm:
        name: pm2
        global: yes
        state: present

    - name: add nginx config
      ansible.builtin.include_role:
        name: geerlingguy.nginx
      vars:
        nginx_vhosts:
          - listen: '80'
            server_name: '158.160.138.32'
            state: 'present'
            filename: 'fixremont-frontend.conf'
            extra_parameters: |
              location / {
                proxy_pass http://127.0.0.1:3000;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Prefix /;
              }
          - listen: '3000'
            server_name: '158.160.138.32'
            state: 'present'
            filename: 'fixremont-backend.conf'
            extra_parameters: |
              location / {
                proxy_pass http://127.0.0.1:8000;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Prefix /;
              }

    - name: create project directory
      ansible.builtin.file:
        path: '{{ remote_app_path }}'
        state: directory

    - name: copy .env file
      ansible.builtin.copy:
        src: '{{ local_app_path }}/.env'
        dest: '{{ remote_app_path }}/.env'

    - name: copy ecosystem.config.js file
      ansible.builtin.copy:
        src: '{{ local_app_path }}/ecosystem.config.js'
        dest: '{{ remote_app_path }}/ecosystem.config.js'

    # - name: install pytho3 and pip
    #   ansible.builtin.include_role:
    #     - name: python3
    #       python3_pyenv: '3.12.x'
